import { StyleSheet } from 'react-native';
import { Typography } from '@/constants/Typography';

export const styles = StyleSheet.create({
  filterPanel: {
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#ECEFF3',
    padding: 16,
  },
  filterOverlay: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  filterBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(17, 24, 39, 0.26)',
  },
  filterSheet: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    overflow: 'hidden',
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  categoryBackBtn: {
    width: 30,
    height: 30,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterMainTitle: {
    fontSize: Typography.size.bodyLg,
    fontWeight: '800',
    color: '#111827',
  },
  filterHeaderHint: {
    marginTop: 2,
    fontSize: Typography.size.caption,
    color: '#9CA3AF',
  },
  filterCardBlock: {
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EDF1F5',
    padding: 12,
  },
  filterTitle: { fontSize: Typography.size.label, color: '#333', fontWeight: '600' },
  filterBlockGap: { marginTop: 14 },
  rangeRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rangeInput: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EBF0',
    paddingHorizontal: 12,
    color: '#111827',
    fontSize: Typography.size.body,
  },
  rangeDivider: { color: '#6B7280', fontSize: Typography.size.caption },
  helperText: { marginTop: 8, color: '#9CA3AF', fontSize: Typography.size.caption },

  typeWrap: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  typeChip: {
    minWidth: 70,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E6EAF0',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  typeChipActive: {
    backgroundColor: '#FFF4DB',
    borderColor: '#F8D58E',
  },
  typeChipText: { color: '#6B7280', fontSize: Typography.size.body, fontWeight: '600' },
  typeChipTextActive: { color: '#C78500' },

  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EDF1F5',
    paddingHorizontal: 12,
    minHeight: 52,
  },
  filterRowRight: { flexDirection: 'row', alignItems: 'center' },
  filterValue: { color: '#6B7280', fontSize: Typography.size.body },

  filterActions: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  resetBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetText: { color: '#374151', fontSize: Typography.size.label, fontWeight: '700' },
  confirmBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F59E0B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmText: { color: '#FFFFFF', fontSize: Typography.size.label, fontWeight: '700' },

  categoryList: {
    maxHeight: 340,
    marginTop: 8,
  },
  categoryItem: {
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EDF1F5',
    marginBottom: 8,
  },
  categoryItemText: { fontSize: Typography.size.body, color: '#111827', fontWeight: '500' },
});
