import { StyleSheet } from 'react-native';

import { Typography } from '@/constants/Typography';

export const styles = StyleSheet.create({
  filterOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  filterBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(44,52,32,0.32)',
  },
  filterSheet: {
    width: '100%',
    maxHeight: '92%',
    backgroundColor: '#FCFAF8',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    overflow: 'hidden',
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  dragHandleContainer: {
    alignItems: 'center',
    marginBottom: 10,
    paddingVertical: 12,
  },
  dragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#DCD4CB',
  },
  filterScrollContent: {
    paddingBottom: 4,
  },
  filterHeaderCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  headerIconBtnPlain: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#F3EFE9',
  },
  filterMainTitle: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '800',
    color: '#2C3420',
  },
  filterCardBlock: {
    borderRadius: 20,
    backgroundColor: '#FBF9F6',
    padding: 16,
    marginBottom: 16,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  filterTitle: {
    fontSize: Typography.size.body,
    lineHeight: Typography.lineHeight.body,
    color: '#2C3420',
    fontWeight: '800',
  },
  inlineClearBtn: {
    marginLeft: 'auto',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#F3EFE9',
  },
  inlineClearText: {
    color: '#7F8671',
    fontSize: Typography.size.footnote,
    lineHeight: Typography.lineHeight.footnote,
    fontWeight: '700',
  },
  rangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  rangeBlock: {
    flex: 1,
    height: 64,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'space-between',
  },
  rangeBlockLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9CA38F',
  },
  rangeBlockValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rangeBlockValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2C3420',
  },
  rangeBlockValueEmpty: {
    color: '#9CA38F',
  },
  rangeDivider: {
    color: '#7F8671',
    fontSize: Typography.size.caption,
    fontWeight: '600',
  },
  dateRangeTriggerActive: {
    borderColor: '#F98C58',
    borderWidth: 1,
  },
  typeWrap: {
    flexDirection: 'row',
    gap: 8,
  },
  typeChip: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeChipActive: {
    backgroundColor: '#F98C58',
  },
  typeChipText: {
    color: '#7F8671',
    fontSize: 15,
    fontWeight: '700',
  },
  typeChipTextActive: {
    color: '#FFFFFF',
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  currencySymbol: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2C3420',
    marginRight: 6,
  },
  amountInput: {
    flex: 1,
    height: 24,
    padding: 0,
    margin: 0,
    fontSize: 15,
    fontWeight: '700',
    color: '#2C3420',
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    height: 54,
  },
  filterRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  filterValue: {
    color: '#9CA38F',
    fontSize: 15,
    fontWeight: '600',
  },
  filterValueActive: {
    color: '#2C3420',
  },
  filterActions: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 12,
  },
  resetBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#EEF3D8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetText: {
    color: '#5C6C38',
    fontSize: 16,
    fontWeight: '800',
  },
  confirmBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#F98C58',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  categoryList: {
    maxHeight: 380,
    marginTop: 10,
  },
  categoryListContent: {
    paddingBottom: 4,
  },
  categoryItem: {
    minHeight: 54,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: '#F6EDE4',
    borderWidth: 1,
    borderColor: 'rgba(110, 125, 66, 0.08)',
    marginBottom: 10,
  },
  categoryItemActive: {
    backgroundColor: '#F98C58',
    borderColor: '#F98C58',
  },
  categoryItemText: {
    fontSize: Typography.size.body,
    lineHeight: Typography.lineHeight.body,
    color: '#2C3420',
    fontWeight: '700',
  },
  categoryItemTextActive: {
    color: '#FFFFFF',
  },
  categoryCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFF9F1',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(110, 125, 66, 0.1)',
  },
  categoryCheckActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
});
