import { StyleSheet } from 'react-native';
import { Typography } from '@/constants/Typography';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    height: 64,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerBtn: { padding: 8 },
  headerTitle: { fontSize: Typography.size.title, fontWeight: '700', color: '#111827' },
  headerRight: { flexDirection: 'row', alignItems: 'center' },
  headerSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  headerSearchBar: {
    height: 48,
    borderRadius: 14,
    backgroundColor: '#FFF9F1',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    flex: 1,
  },
  headerSearchCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  toolbarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  toolbarChip: {
    minHeight: 38,
    borderRadius: 20,
    paddingHorizontal: 12,
    backgroundColor: '#FFF9F1',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  toolbarChipActive: {
    backgroundColor: '#FCCEB4',
  },
  toolbarChipRight: {
    marginLeft: 'auto',
  },
  toolbarChipText: { fontSize: Typography.size.body, color: '#374151', fontWeight: '500' },
  toolbarChipActiveText: { color: '#DD724A' },

  listContent: { paddingBottom: 50 },
  monthHeader: {
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#EEF3D8',
    paddingHorizontal: 14,
    minHeight: 46,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(110, 125, 66, 0.08)',
  },
  monthTitle: { color: '#2C3420', fontSize: Typography.size.label, fontWeight: '700' },
  monthTotal: { fontSize: Typography.size.label, fontWeight: '700' },
  emptyText: { textAlign: 'center', marginTop: 120, color: '#7F8671', fontSize: Typography.size.body },

  searchInput: { flex: 1, color: '#1F2937', fontSize: Typography.size.body },

  appliedHint: {
    position: 'absolute',
    right: 16,
    bottom: 24,
    borderRadius: 999,
    backgroundColor: 'rgba(110, 125, 66, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  appliedHintText: { color: '#FFF', fontSize: Typography.size.caption, fontWeight: '600' },
});
